DROP DATABASE IF EXISTS Bus_station;
CREATE DATABASE Bus_station;

USE Bus_station;

CREATE TABLE Companies(
	Company INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	CompanyName NVARCHAR(510) NOT NULL UNIQUE
);

CREATE TABLE Clients(
	Client INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	FirstName NVARCHAR(510) NOT NULL,
    LastName NVARCHAR(510) NOT NULL,
	Patronymic NVARCHAR(510) NULL,
	Address NVARCHAR(510) NOT NULL,
    Telephone CHAR(30) NOT NULL UNIQUE,
    Email CHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Stations(
	Station INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	StationName NVARCHAR(510) NOT NULL UNIQUE
);

CREATE TABLE Runs(
	Run INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RunNumber NCHAR(10) NOT NULL UNIQUE,
	Company INTEGER NOT NULL REFERENCES Companies(Company) ON DELETE CASCADE ON UPDATE CASCADE,
	BusCapacity INTEGER NOT NULL
);

CREATE TABLE Orders(
	`Order` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Client INTEGER NOT NULL REFERENCES Clients(Client) ON DELETE CASCADE ON UPDATE CASCADE,
	Run INTEGER NOT NULL REFERENCES Runs(Run) ON DELETE CASCADE ON UPDATE CASCADE,
    `From` INTEGER NOT NULL REFERENCES Stations(Station) ON DELETE CASCADE ON UPDATE CASCADE,
    `To` INTEGER NOT NULL REFERENCES Stations(Station) ON DELETE CASCADE ON UPDATE CASCADE,
    Cost INTEGER NOT NULL
);

CREATE TABLE Schedule(
	`Stop` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Run INTEGER NOT NULL REFERENCES Runs(Run) ON DELETE CASCADE ON UPDATE CASCADE,
	Station INTEGER NOT NULL REFERENCES Stations(Station) ON DELETE CASCADE ON UPDATE CASCADE,
	Arrival DATETIME NULL,
	Departure DATETIME NULL,
	
    UNIQUE (Run, Station, Arrival),
    UNIQUE (Run, Station, Departure)
);

CREATE TABLE Costs(
	Run INTEGER NOT NULL REFERENCES Runs(Run) ON DELETE CASCADE ON UPDATE CASCADE,
    `From` INTEGER NOT NULL REFERENCES Stations(Station) ON DELETE CASCADE ON UPDATE CASCADE,
    `To` INTEGER NOT NULL REFERENCES Stations(Station) ON DELETE CASCADE ON UPDATE CASCADE,
    Cost INTEGER NOT NULL,
    
	PRIMARY KEY (Run, `From`, `To`)
);
